import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ConfigProvider } from "antd";
import Header from "@/components/header/Header";
import { AppRouterCacheProvider } from "@mui/material-nextjs/v13-appRouter";
import AuthProvider from "@/context/AuthContext";
import { cookies } from "next/headers";
import { UserCookieResponse } from "@/types/dto/user.dto";
import { decrypt, SessionPayload } from "@/lib/session";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const cookiesStore = cookies(); // Get Cookie on SSR

  const authCookie = await decrypt(cookiesStore.get("login")?.value as string); // Decrypt JWT
  const authInfo: UserCookieResponse = (authCookie as SessionPayload) ?? null; // Convert JWT payload to auth type

  return (
    <html lang="en">
      <body className={inter.className}>
        <AppRouterCacheProvider>
          <ConfigProvider
            theme={{
              components: {
                Collapse: {
                  headerBg: "#ffffff",
                  contentBg: "#ffffff",
                },
              },
            }}
          >
            <AuthProvider authInfo={authInfo}>
              <main className="py-6 px-12 bg-stone-100">
                <Header></Header>
                {children}
              </main>
            </AuthProvider>
          </ConfigProvider>
        </AppRouterCacheProvider>
      </body>
    </html>
  );
}
